apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
    release: prometheus-stack                   ## release / chart name of promethius                 
    self-monitor: "true"
    serviceMonitorSelector: prometheus-stack    ## ? release / chart name of promethius 
    operated-prometheus: "true"
  name: todoapp-smon
  namespace: default   ## Smon Namespace
spec:
  endpoints:
  - interval: 5s
    port: http   ## {{ .Values.service.name }} 
    path: /metrics
  namespaceSelector:
    matchNames:
    - default            ## App Namespace
  selector:
    matchLabels:
      ## {{- include "todoapp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: todoapp           ##  one from todoapp.selectorLabels