apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todoapp.fullname" . }}
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "todoapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "todoapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "todoapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.env.enabled }}
          env:
          {{- if .Values.env.url }}
          - name: MONGO_URI
            value: "mongodb://root:a123456@{{ .Chart.Name }}-mongodb-headless:27017"
          {{- end }}
          {{- if .Values.env.loglevel }}
          - name: LOG_LEVEL
            value: {{ .Values.env.loglevel | quote }}
          {{- end }}
          {{- if .Values.env.metrics }}
          - name: ENABLE_METRICS
            value: {{ .Values.env.metrics | quote }}
          {{- end }}
          {{- else }}
          env:
          {{- if .Values.env.loglevel }}
          - name: LOG_LEVEL
            value: {{ .Values.env.loglevel }}
          {{- else }}
          - name: LOG_LEVEL
            value: "INFO"
          {{- end }}
          {{- if .Values.env.metrics }}
          - name: ENABLE_METRICS
            value: {{ .Values.env.metrics | toString }}
          {{- else }}
          - name: ENABLE_METRICS
            value: "true"
          {{- end }}
          {{- if .Values.env.debug }}
          - name: DEBUG
            value: {{ .Values.env.debug | toString }}
          {{- else }}
          - name: DEBUG
            value: "false"
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
